version: '3.8'
services:
  web:
    image: php:7.4-apache
    container_name: php-web
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
